### ISSUE TITLE
Use another model?

### ISSUE THREAD

**Issue by Godaddy-xie** [VerwimpEli/SSLAD_Track_3#5]
Hallo, I noticed that in track3A the baseline use the ResNet50. Can we use another classifier?, as long as the numbers of parameters < 50M?  
In track3B,  "The method used shoud allow for more than 4 tasks, without big changes in the network structure."  means  we can't use another detector (e.g one-stage detector yolo) and only can modify FastRCNN?

**Comment by VerwimpEli** [comment]
Hi!

- Yes, for track 3A you can use any model, as long as the total numbers of parameters are below 50M
- For track 3B, you're essentially free to choose whatever model you want, so also one-stage detectors like YOLO. What we mean with 'the methods should allow for more than four tasks" -> You can't add a new (large) submodel for every new task and then find a clever way to assign images to the correct submodel. If a fifth task were to be introduced, such systems would require a redesign to also handle the fifth task. Whereas methods like Experience Replay don't have to be adapted to also learn a fifth (and more) task. 

Let me know if something is still unclear :)

Good luck!

**Comment by cvengneer** [comment]
>     * Yes, for track 3A you can use any model, as long as the total numbers of parameters are below 50M

@VerwimpEli 25M or 50M?

**Comment by VerwimpEli** [comment]
25M, sorry for the confusion!
