### ISSUE TITLE
KeyError: 'time'

### ISSUE THREAD

**Issue by githicham** [VerwimpEli/SSLAD_Track_3#6]

**Comment by VerwimpEli** [comment]
Hi,


You're absolutely right. The annotation file of the 3A track is different, so has to be downloaded separately. You can find them on this page: https://competitions.codalab.org/competitions/33830#participate. Then you just have to replace to originals with the new annotation files for the train and validation set. Then everything should be okay!

Please let me know if you don't get it fixed or run into any other issues. Good luck with the challenge!

Best,

Eli
