### ISSUE TITLE
Test set submission issues

### ISSUE THREAD

**Issue by oahzgnaw** [VerwimpEli/SSLAD_Track_3#8]
Thank you for your answer. The json file of the verification set is included in the data set, so I can upload it, but the json file of the test set is not available. Where can I see the json file of the test set? Also, the submission of the test set Is it a zip containing log and txt files like the verification set?sorry to disturb you.

**Comment by VerwimpEli** [comment]
I'm sorry, my bad. I thought you were referring to track 3B. So, for track **3A**, you only have to submit a zip file that contains the `.txt` file and the `.log` file. The server has the correct solutions and will compare your predictions against the correct ones.

**Comment by oahzgnaw** [comment]
> I'm sorry, my bad. I thought you were referring to track 3B. So, for track **3A**, you only have to submit a zip file that contains the `.txt` file and the `.log` file. The server has the correct solutions and will compare your predictions against the correct ones.

Thank you for your answer, but since there is no json file of the test set, the log file generated by the local test shows that the score is 0. Is this normal? After submitting to the server, the real score of the test set will be generated?

**Comment by VerwimpEli** [comment]
Yes, because the `.txt` file has all the predictions of your model. So the server can compare these predictions against the true values. :)

**Comment by oahzgnaw** [comment]
> Yes, because the `.txt` file has all the predictions of your model. So the server can compare these predictions against the true values. :)

Thank you for your answer!
